let initialState = {
    user: {first: "Matt",
            id: 9},
    projects: [{id: "1",
                name: "DIY Chess Board",
                img: "./images/diychess.jpg",
                cost: "$50",
                time: "2 hours",
                supplies: ["16 bronze nuts",
                            "16 bronze bolts",
                            "16 bronze screws",
                            "16 stainless nuts",
                            "16 stainless bolts",
                            "16 stainless screws",
                            "Plywood",
                            "Saw",
                            "Sandpaper",
                            "Wood finish chestnut",
                            "Clear wood finish"],
                instructions: ["1. start the things",
                            "2. Do the things.",
                            "3. Paint the things",
                            "4. Play the chess."],

                },
                {id: "2",
                name: "DIY Chess Board",
                img: "./images/diychess.jpg",
                cost: "$50",
                time: "2 hours",
                supplies: ["16 bronze nuts",
                            "16 bronze bolts",
                            "16 bronze screws",
                            "16 stainless nuts",
                            "16 stainless bolts",
                            "16 stainless screws",
                            "Plywood",
                            "Saw",
                            "Sandpaper",
                            "Wood finish chestnut",
                            "Clear wood finish"],
                instructions: ["1. start the things",
                            "2. Do the things.",
                            "3. Paint the things",
                            "4. Play the chess."],

                },
                {id: "3",
                name: "DIY Chess Board",
                img: "./images/diychess.jpg",
                cost: "$50",
                time: "2 hours",
                supplies: ["16 bronze nuts",
                            "16 bronze bolts",
                            "16 bronze screws",
                            "16 stainless nuts",
                            "16 stainless bolts",
                            "16 stainless screws",
                            "Plywood",
                            "Saw",
                            "Sandpaper",
                            "Wood finish chestnut",
                            "Clear wood finish"],
                instructions: ["1. start the things",
                            "2. Do the things.",
                            "3. Paint the things",
                            "4. Play the chess."],

                },
                {id: "4",
                name: "DIY Chess Board",
                img: "./images/diychess.jpg",
                cost: "$50",
                time: "2 hours",
                supplies: ["16 bronze nuts",
                            "16 bronze bolts",
                            "16 bronze screws",
                            "16 stainless nuts",
                            "16 stainless bolts",
                            "16 stainless screws",
                            "Plywood",
                            "Saw",
                            "Sandpaper",
                            "Wood finish chestnut",
                            "Clear wood finish"],
                instructions: ["1. start the things",
                            "2. Do the things.",
                            "3. Paint the things",
                            "4. Play the chess."],

                }]
};

export default initialState;